app:
  debug: 'false'

db:
  file: 'token.db'

bot:
  url: 'https://t.me/pocket_client_bot'
  secret_token: '6018582589:AAEiYJX76wLJOvD77j4OCcBksqJ-SKuS_78'

server:
  auth_url: 'http://localhost/'

api:
  consumer_key: '106142-308a46906b30d34c4ba78d0'
